# Generated by Django 3.0.5 on 2020-05-07 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0004_friend_friendrequest"),
    ]

    operations = [
        migrations.RemoveField(model_name="friend", name="user1",),
        migrations.RemoveField(model_name="friend", name="user2",),
        migrations.AddField(
            model_name="friend",
            name="current_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="friend",
            name="current_user_friend",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_user_friend",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
