# Generated by Django 3.0.5 on 2020-05-16 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="date_of_comment",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
